###########################################################
#   Description: Generate OTA by GitHub Actions           #
#   Author: Hyy2001X                                      #
###########################################################

name: OTA Generation

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      force_generate:
        description: '强制生成 OTA 包'
        default: 'false'

  #push:
  #  branches: 
  #    - master

  #schedule:
  #  - cron: 0 8 * * 5

  watch:
    types: [started]

jobs:
  Generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Run Auto Generation Script
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        git clone https://github.com/${{github.repository}} work
        cd work
        [ "${{github.event.inputs.force_generate}}" == true ] && force_generate=true || force_generate=false
        bash $GITHUB_WORKSPACE/Scripts/Generate.sh ${{github.repository}} ${force_generate}

    - name: Upload OTA Package
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: work/OTA/*
        file_glob: true
        tag: OTA
        overwrite: true

    - name: Delete old Workflow Runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
